// flow-typed signature: e4d4f643549770a3ead6ed1f0bc695d7
// flow-typed version: <<STUB>>/react-intersection_v1.0.6/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intersection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intersection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intersection/lib' {
  declare module.exports: any;
}

declare module 'react-intersection/lib/intersection-observer' {
  declare module.exports: any;
}

declare module 'react-intersection/lib/IntersectionElement' {
  declare module.exports: any;
}

declare module 'react-intersection/lib/IntersectionRoot' {
  declare module.exports: any;
}

declare module 'react-intersection/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intersection/lib/index' {
  declare module.exports: $Exports<'react-intersection/lib'>;
}
declare module 'react-intersection/lib/index.js' {
  declare module.exports: $Exports<'react-intersection/lib'>;
}
declare module 'react-intersection/lib/intersection-observer.js' {
  declare module.exports: $Exports<'react-intersection/lib/intersection-observer'>;
}
declare module 'react-intersection/lib/IntersectionElement.js' {
  declare module.exports: $Exports<'react-intersection/lib/IntersectionElement'>;
}
declare module 'react-intersection/lib/IntersectionRoot.js' {
  declare module.exports: $Exports<'react-intersection/lib/IntersectionRoot'>;
}
declare module 'react-intersection/lib/types.js' {
  declare module.exports: $Exports<'react-intersection/lib/types'>;
}
